# Relatório  de Análise III

## Imóveis Residenciais

In [19]:
import pandas as pd

In [20]:
dados = pd.read_csv('dados/aluguel.csv', sep = ';')

In [21]:
dados.head(10)

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0
1,Casa,Jardim Botânico,2,0,1,100,7000.0,NaN,NaN
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0
3,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
4,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,NaN
5,Apartamento,Vista Alegre,3,1,0,70,1200.0,NaN,NaN
6,Apartamento,Cachambi,2,0,0,50,1300.0,301.0,17.0
7,Casa de Condomínio,Barra da Tijuca,5,4,5,750,22000.0,NaN,NaN
8,Casa de Condomínio,Ramos,2,2,0,65,1000.0,NaN,NaN
9,Conjunto Comercial/Sala,Centro,0,3,0,695,35000.0,19193.0,3030.0

In [22]:
list(dados['Tipo'].drop_duplicates())

['Quitinete',
 'Casa',
 'Conjunto Comercial/Sala',
 'Apartamento',
 'Casa de Condomínio',
 'Prédio Inteiro',
 'Flat',
 'Loja/Salão',
 'Galpão/Depósito/Armazém',
 'Casa Comercial',
 'Casa de Vila',
 'Terreno Padrão',
 'Box/Garagem',
 'Loft',
 'Loja Shopping/ Ct Comercial',
 'Chácara',
 'Loteamento/Condomínio',
 'Sítio',
 'Pousada/Chalé',
 'Studio',
 'Hotel',
 'Indústria']

In [23]:
residencial = ['Quitinete',
 'Casa',
 'Apartamento',
 'Casa de Condomínio',
 'Casa de Vila']

In [24]:
residencial

['Quitinete', 'Casa', 'Apartamento', 'Casa de Condomínio', 'Casa de Vila']

In [25]:
dados.head(10)

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0
1,Casa,Jardim Botânico,2,0,1,100,7000.0,NaN,NaN
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0
3,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
4,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,NaN
5,Apartamento,Vista Alegre,3,1,0,70,1200.0,NaN,NaN
6,Apartamento,Cachambi,2,0,0,50,1300.0,301.0,17.0
7,Casa de Condomínio,Barra da Tijuca,5,4,5,750,22000.0,NaN,NaN
8,Casa de Condomínio,Ramos,2,2,0,65,1000.0,NaN,NaN
9,Conjunto Comercial/Sala,Centro,0,3,0,695,35000.0,19193.0,3030.0

In [26]:
selecao = dados['Tipo'].isin(residencial)
selecao

0         True
1         True
2        False
3         True
4         True
5         True
6         True
7         True
8         True
9        False
10        True
11        True
12        True
13        True
14        True
15        True
16       False
17       False
18        True
19        True
20        True
21        True
22        True
23        True
24        True
25       False
26       False
27        True
28        True
29       False
         ...
32930     True
32931     True
32932     True
32933     True
32934     True
32935     True
32936     True
32937    False
32938     True
32939    False
32940     True
32941     True
32942    False
32943     True
32944     True
32945     True
32946    False
32947     True
32948    False
32949     True
32950     True
32951     True
32952     True
32953     True
32954    False
32955     True
32956     True
32957     True
32958     True
32959    False
Name: Tipo, Length: 32960, dtype: bool

In [27]:
dados_residencial = dados[selecao]

In [28]:
dados_residencial

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0
1,Casa,Jardim Botânico,2,0,1,100,7000.0,NaN,NaN
3,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
4,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,NaN
5,Apartamento,Vista Alegre,3,1,0,70,1200.0,NaN,NaN
6,Apartamento,Cachambi,2,0,0,50,1300.0,301.0,17.0
7,Casa de Condomínio,Barra da Tijuca,5,4,5,750,22000.0,NaN,NaN
8,Casa de Condomínio,Ramos,2,2,0,65,1000.0,NaN,NaN
10,Apartamento,Centro,1,0,0,36,1200.0,NaN,NaN
11,Apartamento,Grajaú,2,1,0,70,1500.0,642.0,74.0
12,Apartamento,Lins de Vasconcelos,3,1,1,90,1500.0,455.0,14.0
13,Apartamento,Copacabana,1,0,1,40,2000.0,561.0,50.0
14,Quitinete,Copacabana,1,0,0,27,1800.0,501.0,NaN
15,Apartamento,Copacabana,4,3,1,243,13000.0,2000.0,803.0
18,Casa de Condomínio,Taquara,3,1,1,115,2000.0,NaN,NaN
19,Apartamento,Freguesia (Jacarepaguá),3,0,0,54,950.0,300.0,28.0
20,Apartamento,Barra da Tijuca,2,1,1,67,1700.0,589.0,147.0
21,Apartamento,Tijuca,2,1,0,110,1900.0,700.0,138.0
22,Casa de Condomínio,Barra da Tijuca,4,3,2,466,7500.0,2695.0,NaN
23,Apartamento,Olaria,3,1,0,68,1000.0,670.0,NaN
24,Apartamento,Tijuca,2,1,0,78,2000.0,700.0,NaN
27,Apartamento,Ipanema,3,1,1,125,7000.0,2100.0,463.0
28,Apartamento,Tijuca,1,0,0,48,750.0,772.0,25.0
30,Apartamento,Barra da Tijuca,3,3,1,175,4200.0,1500.0,500.0
31,Casa,Campo Grande,4,1,2,400,12000.0,NaN,NaN
32,Apartamento,Botafogo,2,1,0,76,2500.0,740.0,NaN
33,Apartamento,Copacabana,3,1,2,378,10000.0,2150.0,700.0
34,Apartamento,Copacabana,3,0,0,180,5500.0,1780.0,420.0
36,Apartamento,Recreio dos Bandeirantes,3,1,1,105,2300.0,648.0,NaN
37,Apartamento,Leblon,3,1,0,110,3900.0,1500.0,120.0
...,...,...,...,...,...,...,...,...,...
32918,Apartamento,Ipanema,1,0,0,55,2000.0,630.0,19.0
32919,Apartamento,Recreio dos Bandeirantes,3,2,1,100,2500.0,650.0,1864.0
32920,Apartamento,Jardim Botânico,3,1,2,145,5000.0,1296.0,317.0
32921,Apartamento,Recreio dos Bandeirantes,3,2,1,115,2000.0,482.0,166.0
32922,Apartamento,Barra da Tijuca,1,1,0,62,1700.0,945.0,180.0
32924,Casa de Condomínio,Barra da Tijuca,3,5,3,1000,20000.0,3000.0,NaN
32925,Apartamento,Campinho,2,0,0,63,800.0,392.0,NaN
32930,Apartamento,Freguesia (Jacarepaguá),2,1,0,60,500.0,900.0,148.0
32931,Casa,Centro,5,0,1,160,5000.0,NaN,80.0
32932,Apartamento,Todos os Santos,3,0,0,54,1500.0,289.0,35.0
32933,Apartamento,Recreio dos Bandeirantes,2,1,1,105,2100.0,648.0,156.0
32934,Apartamento,Jacarepaguá,2,1,1,78,2200.0,790.0,180.0
32935,Apartamento,Leblon,1,1,1,50,4300.0,1730.0,259.0
32936,Apartamento,Copacabana,2,0,1,70,4100.0,700.0,90.0
32938,Apartamento,Copacabana,1,0,0,50,1950.0,450.0,70.0
32940,Apartamento,Barra da Tijuca,2,1,1,85,2250.0,1561.0,197.0
32941,Apartamento,Barra da Tijuca,3,2,0,98,2300.0,887.0,177.0
32943,Apartamento,Barra da Tijuca,3,2,2,140,5500.0,1900.0,700.0
32944,Apartamento,Recreio dos Bandeirantes,3,2,1,88,1550.0,790.0,NaN
32945,Quitinete,Copacabana,1,0,0,22,1500.0,286.0,200.0
32947,Apartamento,Leblon,3,0,1,80,3000.0,1010.0,249.0
32949,Apartamento,Ipanema,3,1,2,150,15000.0,1400.0,600.0
32950,Apartamento,Tijuca,1,0,0,28,1000.0,360.0,25.0
32951,Apartamento,Vila Valqueire,2,0,0,52,1000.0,550.0,NaN
32952,Casa de Condomínio,Barra da Tijuca,5,3,4,450,15000.0,1711.0,2332.0
32953,Apartamento,Méier,2,0,0,70,900.0,490.0,48.0
32955,Quitinete,Centro,0,0,0,27,800.0,350.0,25.0
32956,Apartamento,Jacarepaguá,3,1,2,78,1800.0,800.0,40.0
32957,Apartamento,São Francisco Xavier,2,1,0,48,1400.0,509.0,37.0
32958,Apartamento,Leblon,2,0,0,70,3000.0,760.0,NaN

In [29]:
list(dados_residencial['Tipo'].drop_duplicates())

['Quitinete', 'Casa', 'Apartamento', 'Casa de Condomínio', 'Casa de Vila']

In [30]:
dados_residencial.shape[0]

22580

In [31]:
dados.shape[0]

32960

In [32]:
dados_residencial.index = range(dados_residencial.shape[0])

In [33]:
dados_residencial

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0
1,Casa,Jardim Botânico,2,0,1,100,7000.0,NaN,NaN
2,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
3,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,NaN
4,Apartamento,Vista Alegre,3,1,0,70,1200.0,NaN,NaN
5,Apartamento,Cachambi,2,0,0,50,1300.0,301.0,17.0
6,Casa de Condomínio,Barra da Tijuca,5,4,5,750,22000.0,NaN,NaN
7,Casa de Condomínio,Ramos,2,2,0,65,1000.0,NaN,NaN
8,Apartamento,Centro,1,0,0,36,1200.0,NaN,NaN
9,Apartamento,Grajaú,2,1,0,70,1500.0,642.0,74.0
10,Apartamento,Lins de Vasconcelos,3,1,1,90,1500.0,455.0,14.0
11,Apartamento,Copacabana,1,0,1,40,2000.0,561.0,50.0
12,Quitinete,Copacabana,1,0,0,27,1800.0,501.0,NaN
13,Apartamento,Copacabana,4,3,1,243,13000.0,2000.0,803.0
14,Casa de Condomínio,Taquara,3,1,1,115,2000.0,NaN,NaN
15,Apartamento,Freguesia (Jacarepaguá),3,0,0,54,950.0,300.0,28.0
16,Apartamento,Barra da Tijuca,2,1,1,67,1700.0,589.0,147.0
17,Apartamento,Tijuca,2,1,0,110,1900.0,700.0,138.0
18,Casa de Condomínio,Barra da Tijuca,4,3,2,466,7500.0,2695.0,NaN
19,Apartamento,Olaria,3,1,0,68,1000.0,670.0,NaN
20,Apartamento,Tijuca,2,1,0,78,2000.0,700.0,NaN
21,Apartamento,Ipanema,3,1,1,125,7000.0,2100.0,463.0
22,Apartamento,Tijuca,1,0,0,48,750.0,772.0,25.0
23,Apartamento,Barra da Tijuca,3,3,1,175,4200.0,1500.0,500.0
24,Casa,Campo Grande,4,1,2,400,12000.0,NaN,NaN
25,Apartamento,Botafogo,2,1,0,76,2500.0,740.0,NaN
26,Apartamento,Copacabana,3,1,2,378,10000.0,2150.0,700.0
27,Apartamento,Copacabana,3,0,0,180,5500.0,1780.0,420.0
28,Apartamento,Recreio dos Bandeirantes,3,1,1,105,2300.0,648.0,NaN
29,Apartamento,Leblon,3,1,0,110,3900.0,1500.0,120.0
...,...,...,...,...,...,...,...,...,...
22550,Apartamento,Ipanema,1,0,0,55,2000.0,630.0,19.0
22551,Apartamento,Recreio dos Bandeirantes,3,2,1,100,2500.0,650.0,1864.0
22552,Apartamento,Jardim Botânico,3,1,2,145,5000.0,1296.0,317.0
22553,Apartamento,Recreio dos Bandeirantes,3,2,1,115,2000.0,482.0,166.0
22554,Apartamento,Barra da Tijuca,1,1,0,62,1700.0,945.0,180.0
22555,Casa de Condomínio,Barra da Tijuca,3,5,3,1000,20000.0,3000.0,NaN
22556,Apartamento,Campinho,2,0,0,63,800.0,392.0,NaN
22557,Apartamento,Freguesia (Jacarepaguá),2,1,0,60,500.0,900.0,148.0
22558,Casa,Centro,5,0,1,160,5000.0,NaN,80.0
22559,Apartamento,Todos os Santos,3,0,0,54,1500.0,289.0,35.0
22560,Apartamento,Recreio dos Bandeirantes,2,1,1,105,2100.0,648.0,156.0
22561,Apartamento,Jacarepaguá,2,1,1,78,2200.0,790.0,180.0
22562,Apartamento,Leblon,1,1,1,50,4300.0,1730.0,259.0
22563,Apartamento,Copacabana,2,0,1,70,4100.0,700.0,90.0
22564,Apartamento,Copacabana,1,0,0,50,1950.0,450.0,70.0
22565,Apartamento,Barra da Tijuca,2,1,1,85,2250.0,1561.0,197.0
22566,Apartamento,Barra da Tijuca,3,2,0,98,2300.0,887.0,177.0
22567,Apartamento,Barra da Tijuca,3,2,2,140,5500.0,1900.0,700.0
22568,Apartamento,Recreio dos Bandeirantes,3,2,1,88,1550.0,790.0,NaN
22569,Quitinete,Copacabana,1,0,0,22,1500.0,286.0,200.0
22570,Apartamento,Leblon,3,0,1,80,3000.0,1010.0,249.0
22571,Apartamento,Ipanema,3,1,2,150,15000.0,1400.0,600.0
22572,Apartamento,Tijuca,1,0,0,28,1000.0,360.0,25.0
22573,Apartamento,Vila Valqueire,2,0,0,52,1000.0,550.0,NaN
22574,Casa de Condomínio,Barra da Tijuca,5,3,4,450,15000.0,1711.0,2332.0
22575,Apartamento,Méier,2,0,0,70,900.0,490.0,48.0
22576,Quitinete,Centro,0,0,0,27,800.0,350.0,25.0
22577,Apartamento,Jacarepaguá,3,1,2,78,1800.0,800.0,40.0
22578,Apartamento,São Francisco Xavier,2,1,0,48,1400.0,509.0,37.0
22579,Apartamento,Leblon,2,0,0,70,3000.0,760.0,NaN

## Exportando a Base de Dados

In [34]:
dados_residencial.to_csv('dados/aluguel_residencial.csv', sep = ';')

In [35]:
dados_residencial_2 = pd.read_csv('dados/aluguel_residencial.csv', sep = ';')

In [36]:
dados_residencial_2

,Unnamed: 0,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0
1,1,Casa,Jardim Botânico,2,0,1,100,7000.0,NaN,NaN
2,2,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
3,3,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,NaN
4,4,Apartamento,Vista Alegre,3,1,0,70,1200.0,NaN,NaN
5,5,Apartamento,Cachambi,2,0,0,50,1300.0,301.0,17.0
6,6,Casa de Condomínio,Barra da Tijuca,5,4,5,750,22000.0,NaN,NaN
7,7,Casa de Condomínio,Ramos,2,2,0,65,1000.0,NaN,NaN
8,8,Apartamento,Centro,1,0,0,36,1200.0,NaN,NaN
9,9,Apartamento,Grajaú,2,1,0,70,1500.0,642.0,74.0
10,10,Apartamento,Lins de Vasconcelos,3,1,1,90,1500.0,455.0,14.0
11,11,Apartamento,Copacabana,1,0,1,40,2000.0,561.0,50.0
12,12,Quitinete,Copacabana,1,0,0,27,1800.0,501.0,NaN
13,13,Apartamento,Copacabana,4,3,1,243,13000.0,2000.0,803.0
14,14,Casa de Condomínio,Taquara,3,1,1,115,2000.0,NaN,NaN
15,15,Apartamento,Freguesia (Jacarepaguá),3,0,0,54,950.0,300.0,28.0
16,16,Apartamento,Barra da Tijuca,2,1,1,67,1700.0,589.0,147.0
17,17,Apartamento,Tijuca,2,1,0,110,1900.0,700.0,138.0
18,18,Casa de Condomínio,Barra da Tijuca,4,3,2,466,7500.0,2695.0,NaN
19,19,Apartamento,Olaria,3,1,0,68,1000.0,670.0,NaN
20,20,Apartamento,Tijuca,2,1,0,78,2000.0,700.0,NaN
21,21,Apartamento,Ipanema,3,1,1,125,7000.0,2100.0,463.0
22,22,Apartamento,Tijuca,1,0,0,48,750.0,772.0,25.0
23,23,Apartamento,Barra da Tijuca,3,3,1,175,4200.0,1500.0,500.0
24,24,Casa,Campo Grande,4,1,2,400,12000.0,NaN,NaN
25,25,Apartamento,Botafogo,2,1,0,76,2500.0,740.0,NaN
26,26,Apartamento,Copacabana,3,1,2,378,10000.0,2150.0,700.0
27,27,Apartamento,Copacabana,3,0,0,180,5500.0,1780.0,420.0
28,28,Apartamento,Recreio dos Bandeirantes,3,1,1,105,2300.0,648.0,NaN
29,29,Apartamento,Leblon,3,1,0,110,3900.0,1500.0,120.0
...,...,...,...,...,...,...,...,...,...,...
22550,22550,Apartamento,Ipanema,1,0,0,55,2000.0,630.0,19.0
22551,22551,Apartamento,Recreio dos Bandeirantes,3,2,1,100,2500.0,650.0,1864.0
22552,22552,Apartamento,Jardim Botânico,3,1,2,145,5000.0,1296.0,317.0
22553,22553,Apartamento,Recreio dos Bandeirantes,3,2,1,115,2000.0,482.0,166.0
22554,22554,Apartamento,Barra da Tijuca,1,1,0,62,1700.0,945.0,180.0
22555,22555,Casa de Condomínio,Barra da Tijuca,3,5,3,1000,20000.0,3000.0,NaN
22556,22556,Apartamento,Campinho,2,0,0,63,800.0,392.0,NaN
22557,22557,Apartamento,Freguesia (Jacarepaguá),2,1,0,60,500.0,900.0,148.0
22558,22558,Casa,Centro,5,0,1,160,5000.0,NaN,80.0
22559,22559,Apartamento,Todos os Santos,3,0,0,54,1500.0,289.0,35.0
22560,22560,Apartamento,Recreio dos Bandeirantes,2,1,1,105,2100.0,648.0,156.0
22561,22561,Apartamento,Jacarepaguá,2,1,1,78,2200.0,790.0,180.0
22562,22562,Apartamento,Leblon,1,1,1,50,4300.0,1730.0,259.0
22563,22563,Apartamento,Copacabana,2,0,1,70,4100.0,700.0,90.0
22564,22564,Apartamento,Copacabana,1,0,0,50,1950.0,450.0,70.0
22565,22565,Apartamento,Barra da Tijuca,2,1,1,85,2250.0,1561.0,197.0
22566,22566,Apartamento,Barra da Tijuca,3,2,0,98,2300.0,887.0,177.0
22567,22567,Apartamento,Barra da Tijuca,3,2,2,140,5500.0,1900.0,700.0
22568,22568,Apartamento,Recreio dos Bandeirantes,3,2,1,88,1550.0,790.0,NaN
22569,22569,Quitinete,Copacabana,1,0,0,22,1500.0,286.0,200.0
22570,22570,Apartamento,Leblon,3,0,1,80,3000.0,1010.0,249.0
22571,22571,Apartamento,Ipanema,3,1,2,150,15000.0,1400.0,600.0
22572,22572,Apartamento,Tijuca,1,0,0,28,1000.0,360.0,25.0
22573,22573,Apartamento,Vila Valqueire,2,0,0,52,1000.0,550.0,NaN
22574,22574,Casa de Condomínio,Barra da Tijuca,5,3,4,450,15000.0,1711.0,2332.0
22575,22575,Apartamento,Méier,2,0,0,70,900.0,490.0,48.0
22576,22576,Quitinete,Centro,0,0,0,27,800.0,350.0,25.0
22577,22577,Apartamento,Jacarepaguá,3,1,2,78,1800.0,800.0,40.0
22578,22578,Apartamento,São Francisco Xavier,2,1,0,48,1400.0,509.0,37.0
22579,22579,Apartamento,Leblon,2,0,0,70,3000.0,760.0,NaN

In [37]:
dados_residencial.to_csv('dados/aluguel_residencial.csv', sep = ';', index = False)

In [38]:
dados_residencial_2 = pd.read_csv('dados/aluguel_residencial.csv', sep = ';')

In [39]:
dados_residencial_2

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0
1,Casa,Jardim Botânico,2,0,1,100,7000.0,NaN,NaN
2,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
3,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,NaN
4,Apartamento,Vista Alegre,3,1,0,70,1200.0,NaN,NaN
5,Apartamento,Cachambi,2,0,0,50,1300.0,301.0,17.0
6,Casa de Condomínio,Barra da Tijuca,5,4,5,750,22000.0,NaN,NaN
7,Casa de Condomínio,Ramos,2,2,0,65,1000.0,NaN,NaN
8,Apartamento,Centro,1,0,0,36,1200.0,NaN,NaN
9,Apartamento,Grajaú,2,1,0,70,1500.0,642.0,74.0
10,Apartamento,Lins de Vasconcelos,3,1,1,90,1500.0,455.0,14.0
11,Apartamento,Copacabana,1,0,1,40,2000.0,561.0,50.0
12,Quitinete,Copacabana,1,0,0,27,1800.0,501.0,NaN
13,Apartamento,Copacabana,4,3,1,243,13000.0,2000.0,803.0
14,Casa de Condomínio,Taquara,3,1,1,115,2000.0,NaN,NaN
15,Apartamento,Freguesia (Jacarepaguá),3,0,0,54,950.0,300.0,28.0
16,Apartamento,Barra da Tijuca,2,1,1,67,1700.0,589.0,147.0
17,Apartamento,Tijuca,2,1,0,110,1900.0,700.0,138.0
18,Casa de Condomínio,Barra da Tijuca,4,3,2,466,7500.0,2695.0,NaN
19,Apartamento,Olaria,3,1,0,68,1000.0,670.0,NaN
20,Apartamento,Tijuca,2,1,0,78,2000.0,700.0,NaN
21,Apartamento,Ipanema,3,1,1,125,7000.0,2100.0,463.0
22,Apartamento,Tijuca,1,0,0,48,750.0,772.0,25.0
23,Apartamento,Barra da Tijuca,3,3,1,175,4200.0,1500.0,500.0
24,Casa,Campo Grande,4,1,2,400,12000.0,NaN,NaN
25,Apartamento,Botafogo,2,1,0,76,2500.0,740.0,NaN
26,Apartamento,Copacabana,3,1,2,378,10000.0,2150.0,700.0
27,Apartamento,Copacabana,3,0,0,180,5500.0,1780.0,420.0
28,Apartamento,Recreio dos Bandeirantes,3,1,1,105,2300.0,648.0,NaN
29,Apartamento,Leblon,3,1,0,110,3900.0,1500.0,120.0
...,...,...,...,...,...,...,...,...,...
22550,Apartamento,Ipanema,1,0,0,55,2000.0,630.0,19.0
22551,Apartamento,Recreio dos Bandeirantes,3,2,1,100,2500.0,650.0,1864.0
22552,Apartamento,Jardim Botânico,3,1,2,145,5000.0,1296.0,317.0
22553,Apartamento,Recreio dos Bandeirantes,3,2,1,115,2000.0,482.0,166.0
22554,Apartamento,Barra da Tijuca,1,1,0,62,1700.0,945.0,180.0
22555,Casa de Condomínio,Barra da Tijuca,3,5,3,1000,20000.0,3000.0,NaN
22556,Apartamento,Campinho,2,0,0,63,800.0,392.0,NaN
22557,Apartamento,Freguesia (Jacarepaguá),2,1,0,60,500.0,900.0,148.0
22558,Casa,Centro,5,0,1,160,5000.0,NaN,80.0
22559,Apartamento,Todos os Santos,3,0,0,54,1500.0,289.0,35.0
22560,Apartamento,Recreio dos Bandeirantes,2,1,1,105,2100.0,648.0,156.0
22561,Apartamento,Jacarepaguá,2,1,1,78,2200.0,790.0,180.0
22562,Apartamento,Leblon,1,1,1,50,4300.0,1730.0,259.0
22563,Apartamento,Copacabana,2,0,1,70,4100.0,700.0,90.0
22564,Apartamento,Copacabana,1,0,0,50,1950.0,450.0,70.0
22565,Apartamento,Barra da Tijuca,2,1,1,85,2250.0,1561.0,197.0
22566,Apartamento,Barra da Tijuca,3,2,0,98,2300.0,887.0,177.0
22567,Apartamento,Barra da Tijuca,3,2,2,140,5500.0,1900.0,700.0
22568,Apartamento,Recreio dos Bandeirantes,3,2,1,88,1550.0,790.0,NaN
22569,Quitinete,Copacabana,1,0,0,22,1500.0,286.0,200.0
22570,Apartamento,Leblon,3,0,1,80,3000.0,1010.0,249.0
22571,Apartamento,Ipanema,3,1,2,150,15000.0,1400.0,600.0
22572,Apartamento,Tijuca,1,0,0,28,1000.0,360.0,25.0
22573,Apartamento,Vila Valqueire,2,0,0,52,1000.0,550.0,NaN
22574,Casa de Condomínio,Barra da Tijuca,5,3,4,450,15000.0,1711.0,2332.0
22575,Apartamento,Méier,2,0,0,70,900.0,490.0,48.0
22576,Quitinete,Centro,0,0,0,27,800.0,350.0,25.0
22577,Apartamento,Jacarepaguá,3,1,2,78,1800.0,800.0,40.0
22578,Apartamento,São Francisco Xavier,2,1,0,48,1400.0,509.0,37.0
22579,Apartamento,Leblon,2,0,0,70,3000.0,760.0,NaN